#!/bin/sh

NAME=BLADERF-AUTOBUILDER

if [ "$1" = "killit" ]
then
    docker kill $NAME
    docker rm $NAME
fi

docker run --detach \
    --name $NAME \
    --mount source=bladerf-builds,target=/data \
    bladerf-autobuild
