#!/bin/sh
if [ -z "$1" ]; then
    echo "usage: $0 git_commit_id"
    exit 1
fi

docker run --detach \
    --name $NAME \
    --mount source=bladerf-builds,target=/data \
    bladerf-autobuild \
    /bladerf/autobuild.sh $1
