#!/bin/sh

NAME=BLADERF-AUTOBUILDER

if [ "$1" = "killit" ]
then
    sudo docker kill $NAME
    sudo docker rm $NAME
fi

sudo docker run --detach -v /opt:/opt:ro -v /srv/bladerf:/srv/bladerf:rw --name $NAME bladerf-autobuild
