#!/usr/bin/expect

# Expect script for installing Altera Quartus
# 
# Copyright (c) 2017 Christof Harnischmacher
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

set timeout -1

set version [lindex $argv 0]
if {$version == ""} {
    set version "17.1"
}

set install_path [lindex $argv 1]
if {$install_path == ""} {
    set install_path "/opt/intelFPGA_lite/$version"
}

spawn /root/quartus/setup.sh

expect {
    "Warning: You don't have enough disk space in"      {
        send_user "Installation failed: $expect_out(buffer)"
        exit 28
    }

    "Press \\\[Enter\\\] to continue"                   { send "\r" ; exp_continue }
    "Do you accept this license?"                       { send "y\r" ; exp_continue }
    "Installation directory"                            { send "$install_path\r" ; exp_continue }
    "Quartus Prime Lite Edition (Free)  \\\[Y/n\\\] :"  { send "y\r"  ; exp_continue }
    "Quartus Prime Lite Edition (Free)  - Quartus Prime Help" { send "n\r" ; exp_continue }
    "Quartus Prime Lite Edition (Free)  - Devices"      { send "y\r" ; exp_continue }
    "Quartus Prime Lite Edition (Free)  - Quartus Prime Update" { send "y\r" ; exp_continue }
    "ModelSim - "                                       { send "n\r" ; exp_continue }
    "Is the selection above correct?"                   { send "y\r" ; exp_continue }
    "Create shortcuts on Desktop"                       { send "n\r" ; exp_continue }
    "Launch Quartus Prime Lite Edition \\\[Y/n\\\]:"    { send "n\r" ; exp_continue }
    "Provide your feedback at"                          { send "n\r" ; exp_continue }

    default {}
}

