#!/bin/sh

NAME=BLADERF-WEB

if [ "$1" = "killit" ]
then
    sudo docker kill $NAME
    sudo docker rm $NAME
fi

sudo docker run --detach -v /srv/bladerf:/srv/bladerf:ro --name $NAME bladerf-buildbot-web
