#!/bin/sh

NAME=BLADERF-WEB

if [ "$1" = "killit" ]
then
    sudo docker.io kill $NAME
    sudo docker.io rm $NAME
fi

sudo docker.io run --detach -v /srv/bladerf:/srv/bladerf:ro --name $NAME bladerf-buildbot-web
